query {
  route(path: "http://graphql.drupal/json") {
    ... on ExternalUrl {
      request {
        json {
          ... on JsonObject {
            node:pathToEntity(type: "node", steps: ["node"]) {
              uuid:entityUuid
            }
          }
        }
      }
    }
  }
}