query {
  string:route(path: "http://graphql.drupal/json/string") {
    request {
      ... on ExternalUrl {
        json {
          ... on JsonLeaf {
            value
          }
        }
      }
    }
  }
  int:route(path: "http://graphql.drupal/json/int") {
    request {
      ... on ExternalUrl {
        json {
          ... on JsonLeaf {
            value
          }
        }
      }
    }
  }
  float:route(path: "http://graphql.drupal/json/float") {
    request {
      ... on ExternalUrl {
        json {
          ... on JsonLeaf {
            value
          }
        }
      }
    }
  }
  bool:route(path: "http://graphql.drupal/json/bool") {
    request {
      ... on ExternalUrl {
        json {
          ... on JsonLeaf {
            value
          }
        }
      }
    }
  }
}
