query {
  route(path: "http://graphql.drupal/json/object") {
    ... on ExternalUrl {
      request {
        json {
          ... on JsonObject {
            keys
            a:path(steps: ["a"]) {
              ... on JsonLeaf {
                value
              }
            }
            b:path(steps: ["b"]) {
              ... on JsonLeaf {
                value
              }
            }
          }
        }
      }
    }
  }
}
