query {
  route(path: "http://graphql.drupal/json") {
    ... on ExternalUrl {
      request {
        json {
          ... on JsonObject {
            url:pathToUrl(steps: ["url"]) {
              ... on ExternalUrl {
                request {
                  json {
                    ... on JsonLeaf {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}